# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/SampleTests/SampleTests.csproj'
    feedsToUse: 'select'
  displayName: '.NET Core (Restore)'
- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/SampleTests/SampleTests.csproj'
    arguments: '--framework netcoreapp3.0 --configuration Release --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
  displayName: '.NET Core (Publish)'
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '*.dll'
    searchFolder: '$(Build.ArtifactStagingDirectory)'
    vsTestVersion: 'toolsInstaller'
    otherConsoleOptions: '/framework:".NETCoreApp,Version=v3.0"'
